### PR TITLE
Bug/138 import error handling

### LINKED ISSUE #138: SQL Import Error Handling
### Summary
Currently, when executing an IMPORT statement via transaction in Go, only a generic broken pipe network error is returned in certain failure scenarios, making root cause analysis difficult. Instead, the system should surface the actual SQL error, such as mismatched columns, to assist with debugging.

### Steps to Reproduce:
Run the following Go code to import a CSV into a database table:
```go
transaction, err := database.Begin()
if err != nil {
    return err
}
defer transaction.Commit()

importSQL := fmt.Sprintf(`import into "%s"."%s" from local csv file '%s'`, schema, table, filename)
_, err = transaction.Exec(importSQL)
fmt.Println(err)

```

Provide a CSV file where the number of columns does not match the destination table definition.

### Current Behavior:
Instead of receiving a clear SQL error, such as:

> ETL-6009: Number of columns in source (=2) and destination (=1) table differs

The driver returns:
> write tcp 172.17.0.2:42590->10.0.1.2:8563: write: broken pipe

This hides the underlying SQL failure and makes troubleshooting difficult.

### Expected Behavior:
The system should surface the actual SQL engine error, e.g.:

> ETL-6009: Number of columns in source (=2) and destination (=1) table differs

If the connection drops due to an application-level SQL error, the root cause should still be accessible to the client code.

### PR DESCRIPTION
**Pull request by YotillaAntoni**
Closes #138

### CODE REVIEW

File: pkg/proxy/proxy.go [hunk 1]
```diff
@@ -99,7 +99,6 @@ func (p *Proxy) SendFile(ctx context.Context, file *os.File, rowSeparator string
 
 	for {
 		if ctx.Err() != nil {
-			p.Close()
```
Comment (YotillaAntoni) [inline pkg/proxy/proxy.go:102]: the closing is handled by the calling code, there is no need to handle it here

File: pkg/connection/connection.go [hunk 2]
```diff
@@ -196,9 +196,14 @@ func (c *Connection) exec(ctx context.Context, query string, args []driver.Value
 			return nil, err
 		}
 
-		defer importStatement.Close()
 		query = importStatement.GetUpdatedQuery()
-		errs.Go(func() error { return importStatement.UploadFiles(errctx) })
+		go func() {
+			defer importStatement.Close()
```
Comment (tkilias) [inline pkg/connection/connection.go:201]: Maybe a comment on why we need to close the import statement here and why we can't run this goroutine in the error group might be advisable.

File: itest/integration_test.go [hunk 3]
```diff
@@ -604,6 +604,32 @@ func (suite *IntegrationTestSuite) TestSimpleImportStatement() {
...
+	database := suite.openConnection(suite.createDefaultConfig())
+	ctx := context.Background()
+	schemaName := "TEST_SCHEMA_8"
+	tableName := "TEST_TABLE"
+	_, _ = database.ExecContext(ctx, "CREATE SCHEMA "+schemaName)
+	defer suite.cleanup(database, schemaName)
+	_, _ = database.ExecContext(ctx, fmt.Sprintf("CREATE TABLE %s.%s (a int)", schemaName, tableName))
+
+	_, err := database.ExecContext(ctx, fmt.Sprintf(`IMPORT INTO %s.%s FROM LOCAL CSV FILE 'wrong.csv'`, schemaName, tableName))
+	suite.ErrorContains(err, "E-EGOD-11: execution failed with SQL error code '42636' and message 'ETL-5105: Following error occured while reading data from external connection")
```
Comment (kaklakariada) [inline itest/integration_test.go:630]: This error comes from the DB. Would it be possible to already check if the file exists locally before executing the statement? If this is more complicated we could do this in a separate issue.

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: itest/integration_test.go (hunk 3 above)
Comment (YotillaAntoni) [reply itest/integration_test.go:630]: We should definitely do this at some point. But it's more complicated, and replacing the current integration tests that checks for the upload failure it's tricky. I created this separate issue https://github.com/exasol/exasol-driver-go/issues/141

File: pkg/connection/connection.go [hunk 4]
```diff
@@ -197,7 +197,10 @@ func (c *Connection) exec(ctx context.Context, query string, args []driver.Value
 		}
 
 		query = importStatement.GetUpdatedQuery()
+		// The upload it's not part of the errgroup to avoid that an error in the upload prevents the statement from
+		// finishing and returning the error from the database.
 		go func() {
+			// Close right after the upload to ensure that the IMPORT statement can proceed in case of  error
```
Comment (tkilias) [inline pkg/connection/connection.go:203]:
```suggestion
			// Close right after the upload to ensure that the IMPORT statement can proceed in case of an error
```
