### PR TITLE
Bug/146 issue closing connection

### LINKED ISSUE #146: Bug: Partial file transfer error during import statement execution
### **Description:**
We are currently unable to import larger files. Attempts to import result in the following error:

```
E-EGOD-11: execution failed with SQL error code '42636' and message 'ETL-5105: Following error occurred while reading data from external connection [http://XXX.XXX.XXX.XXX:37117/data.csv failed after 248782 bytes. [transfer closed with outstanding read data remaining],[18],[Transferred a partial file]]'
```

### **Root cause:**
The issue appears to be in the implementation of the import logic in connection.go. For file uploads, a separate goroutine is started:

```go
go func() {
    // Close right after the upload to ensure that the IMPORT statement can proceed in case of an error
    defer importStatement.Close()
    uploadErr := importStatement.UploadFiles(errctx)
    if uploadErr != nil {
        logger.ErrorLogger.Printf("Error uploading files: %v", uploadErr)
    }
}()
```

The problem is that importStatement.Close() is executed as soon as the upload of the data finishes.

In the second goroutine where the import statement is processed:
```go
if len(args) == 0 {
    errs.Go(c.executeSimpleWrapper(errctx, query, result))
} else {
    errs.Go(c.executePreparedStatementWrapper(errctx, query, args, result))
}
```

Not all data can be read here, which leads to the error above and aborts the import with a message indicating that only a partial file was transferred.

### **Impact:**
- Large file imports fail completely.
- The current implementation closes the import statement too early, before the import process can consume all uploaded data.

### PR DESCRIPTION
**Pull request by antonireus**
Closes #146

### CODE REVIEW

File: pkg/connection/connection.go [hunk 1]
```diff
@@ -195,18 +195,18 @@ func (c *Connection) exec(ctx context.Context, query string, args []driver.Value
...
-		// finishing and returning the error from the database.
-		go func() {
-			// Close right after the upload to ensure that the IMPORT statement can proceed in case of an error
-			defer importStatement.Close()
+		errs.Go(func() error {
 			uploadErr := importStatement.UploadFiles(errctx)
 			if uploadErr != nil {
 				logger.ErrorLogger.Printf("Error uploading files: %v", uploadErr)
+				// In case of error we close the statement immediately, so the execute step can proceed.
+				importStatement.Close()
```
Comment (antonireus) [inline pkg/connection/connection.go:206]: In general we need to close the statement at the end of the function with the defer, except in the event of an error, where we need to immediately close it otherwise the execution go routine would get blocked

**Review by ckunki — APPROVED** [review]
