### PR TITLE
#108: Convert args for prepared statements to expected type

### LINKED ISSUE #108: E-EGOD-11: execution failed with SQL error code '00000' and message 'getDouble: JSON value is not a double
Hallo,

if you try to insert a decimal value with a prepared statement you will get an JSON error.

**Error:**
panic: E-EGOD-11: execution failed with SQL error code '00000' and message 'getDouble: JSON value is not a double

**Table structure:**
`create or replace table work.dummy (a integer, b float);`

**Go Code:**
`	
	exadb, err := sql.Open("exasol", config.String())
	if err != nil {
		panic(err)
	}
	defer exadb.Close()

	stmt, err := exadb.Prepare("insert into work.dummy values(?,?)")
	if err != nil {
		panic(err)
	}

	_, err = stmt.Exec(1, 1)
	if err != nil {
		panic(err)
	}
`

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #108

### CODE REVIEW

File: pkg/connection/prepared_stmt_converter.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+
+	"github.com/exasol/exasol-driver-go/pkg/errors"
+	"github.com/exasol/exasol-driver-go/pkg/types"
+)
+
+func convertArg(arg driver.Value, colType types.SqlQueryColumnType) (interface{}, error) {
+	dataType := colType.Type
+	switch dataType {
+	case "DOUBLE":
+		switch arg := arg.(type) {
```
Comment (pj-spoelders) [inline pkg/connection/prepared_stmt_converter.go:17]: If I'd had to take a guess this is probably where the quality gate failed.

Comment (pj-spoelders) [reply pkg/connection/prepared_stmt_converter.go:17]: You probably need this: https://stackoverflow.com/questions/68578/multiple-cases-in-switch-statement

**Review by pj-spoelders — CHANGES_REQUESTED** [review]
Looks good, as always, but you'll need to address the quality gate's comments.

**Review by pj-spoelders — APPROVED** [review]
Ok, approved!
