### PR TITLE
#98 Fixed detection of IMPORT LOCAL FILE

### LINKED ISSUE #98: Invalid SQL Parsing
When executing an insert statement that contains 'import into ' as a value the following error is raised. 

E-EGOD-27: could not parse import query

Example statement.
`
insert into table1 values ('import into {{dest.schema}}.{{dest.table}} )
   from local csv file ''{{file.path}}'' ');
`

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #98

### CODE REVIEW

File: internal/utils/helper_test.go [hunk 1]
```diff
@@ -26,7 +26,27 @@ func TestNamedValuesToValuesInvalidName(t *testing.T) {
...
+		{name: "select query unsupported", query: "select * from schema.table", expectedResult: false},
+		{name: "import in string with placeholders", query: "insert into table1 values ('import into {{dest.schema}}.{{dest.table}} ) from local csv file ''{{file.path}}'' ');", expectedResult: false},
+		{name: "import in string", query: "insert into table1 values ('import into schema.table from local csv file ''/path/to/filename.csv''');", expectedResult: false},
+		{name: "import in string with schema", query: "insert into schema.tab1 values ('IMPORT into schema.table FROM LOCAL CSV file ''/path/to/filename.csv'';')", expectedResult: false},
+	}
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			assert.Equal(t, test.expectedResult, IsImportQuery(test.query))
+		})
+	}
```
Comment (ckunki) [inline internal/utils/helper_test.go:49]: :+1:

File: itest/integration_test.go [hunk 2]
```diff
@@ -327,6 +327,27 @@ func (suite *IntegrationTestSuite) TestSimpleImportStatement() {
...
+	affectedRows, _ := result.RowsAffected()
+	suite.Equal(int64(1), affectedRows)
+
+	rows, _ := database.Query(fmt.Sprintf("SELECT * FROM %s.%s", schemaName, tableName))
+	suite.assertTableResult(rows,
+		[]string{"TEXT"},
+		[][]interface{}{{"import into {{dest.schema}}.{{dest.table}} ) from local csv file '{{file.path}}' "}},
+	)
+}
+
```
Comment (ckunki) [inline itest/integration_test.go:350]: :+1:

File: internal/utils/helper.go [hunk 3]
```diff
@@ -39,15 +35,21 @@ func BoolToPtr(b bool) *bool {
...
 
+var localImportRegex = regexp.MustCompile(`(?ims)^\s*IMPORT[\s(]+.+FROM\s+LOCAL\s+CSV.*$`)
+
 func IsImportQuery(query string) bool {
 	return localImportRegex.MatchString(query)
 }
 
+const ROW_SEPARATOR_PLACEHOLDER = "RowSeparatorPlaceholder"
+
+var rowSeparatorQueryRegex = regexp.MustCompile(fmt.Sprintf(`(?i)(ROW\s+SEPARATOR\s+=\s+(["|'])?(?P<%s>[a-zA-Z]+)(["|']?))`, ROW_SEPARATOR_PLACEHOLDER))
```
Comment (ckunki) [inline internal/utils/helper.go:46]: Would it be possible to split the regex into multiple lines and add some comments?
Esp. maybe also about the algo / approach?
And maybe on the modifiers, `(?i)` (case-insensitive, I guess)

**Review by ckunki — CHANGES_REQUESTED** [review]
See my comments

**Review by ckunki — APPROVED** [review]
